AllCops:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'db/**/*'
    - 'node_modules/**/*'
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Rails/FilePath:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Style/GuardClause:
  Enabled: false
Rails/Present:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Lint/UselessMethodDefinition:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/SymbolArray:
  Enabled: false